### ISSUE TITLE
Ecotrust dev guide

### ISSUE THREAD

**Issue by perrygeo** [Ecotrust/ks-tickets#1]
- [ ] setup and install notes
- [ ] document best practices
- [ ] workflows
- [ ] anatomy of a web app, etc

**Comment by rhodges** [comment]
@perrygeo I've started a document and some templates for per-project documents in the O365 "Project Management" folder.
It's still very much in its infancy, and has some deviation from how we do things now (particularly around git branch and password mgmt) but I'm getting fairly excited about it. Getting the rest of these docs in place will be very helpful as well.
